In [14]:
import numpy as np
x = np.array([[1,2], [3,4]], dtype=np.float)
y = np.array([[5,6], [7,8]], dtype=np.float)
#print(x, y)
#print(x)
#print(y)
print(x + y)
print(np.add(x,y))
print(x - y)
print(np.subtract(x,y))
print(x / y)
print(np.divide(x,y))
print(np.sqrt(x))

print(np.sum(x)) # 1,2,3,4 => 10.0
print(np.sum(x, axis=0)) # col
print(np.sum(x, axis=1)) # row


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
10.0
[4. 6.]
[3. 7.]


In [22]:
#print(x)
#print(x.T)
z = np.array([[1,2],[3,4],[5,6]])
print(z.shape)
print(z)
print(z.T)
print(z.T.shape)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
(2, 3)


In [27]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y1 = np.array([1,0,1])
y2 = x1 + y1
print(x1.shape)
print(y1.shape)
print(y2.shape)
print(y2)

(4, 3)
(3,)
(4, 3)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
