In [20]:
import numpy as np
a = np.array([1,2,3])
print(a)
a1 = np.array((1,2,3))
print(a1)
a2 = np.array([1,2,3], dtype=np.float)
print(a2)
print(a2.shape)
print(a2.dtype)
a3 = np.zeros((3,3))
print(a3)
print(a3.ndim)
a4 = np.zeros((3,3,3))
print(a4.ndim)
a5 = np.empty((2,3))
print(a5)
a5.shape = (3,2)
print(a5)
print(a5.shape)

[1 2 3]
[1 2 3]
[1. 2. 3.]
(3,)
float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
3
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)


In [33]:
# Index, Slicing
import numpy as np
a = np.arange(10)
#print(a[0])
#print(a[1])
#for i in range(10):
#    print(a[i])
print(a[2:])
print(a[0:2])
print(a[:3])
print(a[2:5])

[2 3 4 5 6 7 8 9]
[0 1]
[0 1 2]
[2 3 4]


In [62]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a.ndim)
print(a.dtype)
a[0:]
a[1]
a[2]
a[1:] 
a[1:2,1:]
a[0,1:2] = 100
# a[rows, cols]

(3, 3)
2
int32


array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [71]:
import numpy as np
a = np.array([[0,1,2], [3,4,5],[6,7,8],[9,10,11]])
a.shape
a.dtype
a.ndim
a[1:4, 1:3]
a[:,:]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
import numpy as np
data = np.loadtxt(fname="village_population.csv",
                 encoding="utf-8", dtype=np.str,
                 delimiter=",", usecols=range(0,104))
type(data)
data.shape

(3830, 104)

In [86]:
data2 = data[1:,:]
data2.shape

(3829, 104)