In [32]:
import numpy as np
data = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
data.shape
data.ndim

print(data[0])
print(data[1])
print(data[2])
data[data > 4]

data2 = np.array(['Bob', 'John', 'Bob'])
data2.dtype
data2 == 'Bob'
data == 1
data[data > 3]
print("......")
data3 = np.array([1,2,3,4,5,6,7,8,9])
print(data3.shape)
print(data3.ndim)
print(data3.mean())
print(data3.max())
print(data3.min())
print(data3.sum())
data4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data4.shape)
print(data4.ndim)
print(data4.mean())
print(data4.max())
print(data4.min())
print(data4.sum())
data4[0].mean()

[0 1 2]
[3 4 5]
[6 7 8]
......
(9,)
1
5.0
9
1
45
(3, 3)
2
5.0
9
1
45


2.0