In [23]:
import numpy as np
a = np.array([1,2,3,4])
print("before",  a)
a[1:3] = 6
print("after",  a)

b = np.array([[1,2,3,4],['a','b','c','d']])
print(b)
print(b.T)

c= np.array([[[1,2,3],['a','b','c']],[[4,5,6],['d','e','f']],[[7,8,9],['g','h','i']]])
print("\n c's shape is " , c.shape)
print(c)

before [1 2 3 4]
after [1 6 6 4]
[['1' '2' '3' '4']
 ['a' 'b' 'c' 'd']]
[['1' 'a']
 ['2' 'b']
 ['3' 'c']
 ['4' 'd']]

 c's shape is  (3, 2, 3)
[[['1' '2' '3']
  ['a' 'b' 'c']]

 [['4' '5' '6']
  ['d' 'e' 'f']]

 [['7' '8' '9']
  ['g' 'h' 'i']]]


In [32]:
###########Mask
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
datas = np.random.randn(7,4)
print(datas)
print(names.T)

print(names == 'Bob')
mask = (names == 'Bob')
#mask가 각 row에 매칭된걸 볼 수 있음
print( datas[mask] )


[[ 0.96812691  2.03719251 -0.14634755  0.57606248]
 [-0.12794452 -1.1885047  -0.90225864  1.14406536]
 [-1.62824167 -0.20278646 -0.56648664  0.06556861]
 [-0.7035173  -0.85953944  1.23288312  1.17085971]
 [-0.39593485 -1.32673141  0.31648892 -1.93731036]
 [-0.15847244 -0.39972344 -1.87449088 -0.37765418]
 [-0.09098446 -0.85846814 -0.49212395  0.27538109]]
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[ True False False  True False False False]
[[ 0.96812691  2.03719251 -0.14634755  0.57606248]
 [-0.7035173  -0.85953944  1.23288312  1.17085971]]


In [38]:
##조건주기 : 0보다 작은 애들은 다 0으로 
datas[datas < 0] = 0
datas

array([[0.96812691, 2.03719251, 0.        , 0.57606248],
       [0.        , 0.        , 0.        , 1.14406536],
       [0.        , 0.        , 0.        , 0.06556861],
       [0.        , 0.        , 1.23288312, 1.17085971],
       [0.        , 0.        , 0.31648892, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.27538109]])

In [73]:
#팬시색인
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)
print("\n" , arr[[0,4,3,1]])

arr2 = np.arange(32).reshape((8,4))
print("\n", arr2)
print("\n arr2[[1,5,6,2],[0,3,1,2]] : \n ", arr2[[1,5,6,2],[0,3,1,2]]) #원하는 모양이 아님
print("\n arr2[[1,5,6,2]][ :, [0,3,1,2]] : \n ", arr2[[1,5,6,2]][ :, [0,3,1,2]] )
print("\n arr2[np.ix_([1,5,6,2],[0,3,1,2])]: \n ", arr2[np.ix_([1,5,6,2],[0,3,1,2])] )


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]

 [[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

 arr2[[1,5,6,2],[0,3,1,2]] : 
  [ 4 23 25 10]

 arr2[[1,5,6,2]][ :, [0,3,1,2]] : 
  [[ 4  7  5  6]
 [20 23 21 22]
 [24 27 25 26]
 [ 8 11  9 10]]

 arr2[np.ix_([1,5,6,2],[0,3,1,2])]: 
  [[ 4  7  5  6]
 [20 23 21 22]
 [24 27 25 26]
 [ 8 11  9 10]]


In [87]:
#배열 연산으로 조건절 표현
xarr = np.array([1.1,1.2,1.3,1.4])
yarr = np.array([2.1,2.2,2.3,2.4])
cond = np.array([True,False,False,True])

#1.순수 python
res = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
# y가 True면 x False면 c
print("res" ,res) #but 다차원에서는 사용할 수 없고, 느리다

#2.where 
res2 = np.where(cond,xarr,yarr) # 2,3 인자는 배열이 아니어도 괜찮다.
print("res2" ,res2)

#3. where의 사용
res3 = np.where(res2 < 2, 0.0 ,res2)
print("res3" ,res3)

res [1.1, 2.2, 2.3, 1.4]
res2 [1.1 2.2 2.3 1.4]
res3 [0.  2.2 2.3 0. ]
