In [32]:
import numpy as np

arr = np.array([1,2,3,4], dtype = np.float64) #기본형
print(arr)

arr1 = np.array([1,2,3,4], dtype = np.int64)
print(arr1)

zeros = np.zeros((3,6))
print(zeros)

ones = np.ones((3,6))
print(ones)

empty = np.empty((2,3))
print(empty)

arange = np.arange(10)
print(arange)

v_type = np.array( ['1.3','1.2','3'] , dtype = np.string_)
print(type(v_type[0]))
print(v_type)
#astype을 호출하면 항상 새로운 배열 생성 (데이터 복사)
v2 = v_type.astype(float) #알아서 알맞는 타입 (np.float64 로 변경)
print(v2)
print(type(v2[0]))

v2 = v_type.astype(v_type.dtype) #다른 객체의 데이터 타입을 동일하게 맞춰줄 수 있음
print(type(v2[0]))




[1. 2. 3. 4.]
[1 2 3 4]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.bytes_'>
[b'1.3' b'1.2' b'3']
[1.3 1.2 3. ]
<class 'numpy.float64'>
<class 'numpy.bytes_'>


In [56]:

#### bool
name = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
name1 = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe','Bob'])
data = np.random.randn(7,4)
print(name)
print(data)

##bool 연산
name_bool = 'Bob'==name
print(name_bool)
print(data[name == 'Bob']) # Data의 각 행을 name과 대치시키고 비교

print("Bob or Will")
print(type(name[0]))
mask = (name == 'Bob' | name == 'Will')
#print(data[mask]) # Data의 각 행을 name과 대치시키고 비교

#print(data[name1 == 'Bob']) # 이거는 행의 수가 맞지 않아서 에러난다.

#열 선택해서 가져오기
print(data[name == 'Bob',2:])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.2625898   0.67767224  0.27498008  1.49160533]
 [ 0.21582177  1.11270595 -0.96215815  2.30934014]
 [-1.47674799 -0.51345749 -0.19703879  0.27210995]
 [-0.70094414 -2.5734711   1.43924277  0.167313  ]
 [-0.25581829  0.93130263 -0.40947225 -1.97802452]
 [-1.15438463 -0.96413227 -0.46184502 -0.18913074]
 [-0.24848028 -1.06630254  0.21113868  1.2121385 ]]
[ True False False  True False False False]
[[-1.2625898   0.67767224  0.27498008  1.49160533]
 [-0.70094414 -2.5734711   1.43924277  0.167313  ]]
Bob or Will
<class 'numpy.str_'>


TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''